spring.datasource.url=jdbc:mysql://localhost:3306/Projet_PI?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081

stripe.api.key=${STRIPE_SECRET_KEY}
#stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

jwt.secret=mySecretKeymySecretKeymySecretKeymySecretKey123456
jwt.expiration=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nablinesrine113@gmail.com
spring.mail.password=lcaprubpaznbkqxm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.debug=true
logging.level.org.springframework.mail=DEBUG

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com